site_name: xDuinoRails Motor Control bEMF HAL
docs_dir: docs
theme:
  name: material
  language: en
nav:
  - 'index.md'
  - 'User Manual': 'USER_MANUAL.md'
  - 'How To Use': 'HOW_TO_USE.md'
  - 'Supported Hardware':
    - 'Seeed Studio XIAO RP2040': 'SEEED_XIAO_RP2040.md'
    - 'Motor Driver ICs': 'MOTOR_DRIVER_ICS.md'
  - 'Specifications':
    - 'Core Concepts': 'specification/CORE_CONCEPTS.md'
    - 'Developer Reference': 'specification/DEVELOPER_REFERENCE.md'
    - 'Hardware Control': 'specification/HARDWARE_CONTROL.md'
    - 'BEMF Measurement': 'specification/BEMF_MEASUREMENT_TECHNIQUES.md'
    - 'PWM Frequencies': 'specification/PWM_FREQUENCIES.md'
    - 'Discrete H-Bridge Plan': 'specification/DISCRETE_H_BRIDGE_PLAN.md'
    - 'Technical Debts': 'specification/TECHNICAL_DEBTS.md'
    - 'Testing Improvements': 'specification/TESTING_IMPROVEMENTS.md'
  - 'Contributing': 'specification/CONTRIBUTING.md'
  - 'Roadmap': 'specification/ROADMAP.md'
