[env:seeed_xiao_rp2040]
platform = raspberrypi
board = seeed_xiao_rp2040
framework = arduino
board_build.core = earlephilhower

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

[env:bbcmicrobit_v2]
platform = nordicnrf52
board = bbcmicrobit_v2
framework = mbed

[env:samd21_xpro]
platform = atmelsam
board = samd21_xpro
framework = arduino

[env:nucleo_f103rb]
platform = ststm32
board = nucleo_f103rb
framework = arduino
