[platformio]

[env:seeed_xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
board_build.core = earlephilhower
framework = arduino
build_flags =
    -D USE_IRQ_TRIGGER
lib_deps =
    adafruit/Adafruit NeoPixel
    mathertel/RotaryEncoder

[env:seeed_xiao_rp2040_timer_bemf]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
board_build.core = earlephilhower
framework = arduino
build_flags =
    -D USE_IRQ_TRIGGER
lib_deps =
    adafruit/Adafruit NeoPixel
    mathertel/RotaryEncoder

[env:seeed_xiao_rp2040_adc_debug]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
board_build.core = earlephilhower
framework = arduino
build_flags =
    -D USE_IRQ_TRIGGER
lib_deps =
    adafruit/Adafruit NeoPixel
    mathertel/RotaryEncoder

[env:seeed_xiao_rp2040_led]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
board_build.core = earlephilhower
framework = arduino
build_flags =
    -D LED_EDITION
    -D USE_IRQ_TRIGGER
lib_deps =
    adafruit/Adafruit NeoPixel
    mathertel/RotaryEncoder

[env:seeed_xiao_rp2040_minimal_dcc_nmra]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
board_build.core = earlephilhower
framework = arduino
build_flags =
    -D USE_IRQ_TRIGGER
    -D USE_NMRA_DCC
lib_deps =
    adafruit/Adafruit NeoPixel
    mathertel/RotaryEncoder
    mrrwa/NmraDcc

[env:seeed_xiao_rp2040_minimal_dcc_motorola]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
board_build.core = earlephilhower
framework = arduino
build_flags =
    -D USE_IRQ_TRIGGER
    -D USE_MAERKLIN_MOTOROLA
lib_deps =
    adafruit/Adafruit NeoPixel
    mathertel/RotaryEncoder
    Laserlicht/MaerklinMotorola
