@startuml
!theme vibrant
scale 1200 width

concise "CPU" as CPU
concise "PWM Wrap IRQ" as PWM_IRQ
concise "Timer Alarm" as ALARM
concise "ADC" as ADC
concise "DMA" as DMA
concise "DMA IRQ" as DMA_IRQ
analog "PWM Counter" as PWM_CNT
robust "PWM Compare A" as PWM_COMPA
binary "Internal PWM (A)" as PWM_INT
binary "External PWM (A)" as PWM_EXT
robust "ADC CTRL Reg" as ADC_CTRL
robust "ADC FIFO" as ADC_FIFO

@0
PWM_CNT is "0"
PWM_COMPA is "300"
ADC_CTRL is "Disabled"
ADC_FIFO is "Empty"

/' --- Cycle 1 --- '/
@60
PWM_CNT is "0"
PWM_IRQ is "Active"
CPU is "Active"
@62
PWM_IRQ is "Idle"
CPU is "Idle"

@65
ALARM is "Active"
CPU is "Active"
@66
ALARM is "Idle"
ADC is "Active"
CPU is "Active"
ADC_CTRL is "EN,START_ONCE"
@67
CPU is "Idle"
DMA is "Transferring"
ADC -> DMA : DREQ
ADC_FIFO is "Filling"
@68
ADC -> DMA : DREQ
@69
ADC -> DMA : DREQ
@70
ADC -> DMA : DREQ

@75
DMA is "Idle"
ADC is "Idle"
DMA_IRQ is "Active"
ADC_CTRL is "Disabled"
ADC_FIFO is "Full"
@76
CPU is "Active"
@78
DMA_IRQ is "Idle"
CPU is "Idle"
ADC_FIFO is "Empty"

@60
PWM_CNT is "0"
PWM_INT is 1
PWM_EXT is 0
@67.5
PWM_CNT is "300"
PWM_INT is 0
PWM_EXT is 1
@85
PWM_CNT is "1000"
@102.5
PWM_CNT is "300"
PWM_INT is 1
PWM_EXT is 0
@110
PWM_CNT is "0"
PWM_INT is 1
PWM_EXT is 0

/' --- Cycle 2 --- '/
@110
PWM_IRQ is "Active"
CPU is "Active"
@112
PWM_IRQ is "Idle"
CPU is "Idle"

@115
ALARM is "Active"
CPU is "Active"
@116
ALARM is "Idle"
ADC is "Active"
CPU is "Active"
ADC_CTRL is "EN,START_ONCE"
@117
CPU is "Idle"
DMA is "Transferring"
ADC -> DMA : DREQ
ADC_FIFO is "Filling"
@118
ADC -> DMA : DREQ
@119
ADC -> DMA : DREQ
@120
ADC -> DMA : DREQ

@125
DMA is "Idle"
ADC is "Idle"
DMA_IRQ is "Active"
ADC_CTRL is "Disabled"
ADC_FIFO is "Full"
@126
CPU is "Active"
@128
DMA_IRQ is "Idle"
CPU is "Idle"
ADC_FIFO is "Empty"

@110
PWM_CNT is "0"
PWM_INT is 1
PWM_EXT is 0
@117.5
PWM_CNT is "300"
PWM_INT is 0
PWM_EXT is 1
@135
PWM_CNT is "1000"
@152.5
PWM_CNT is "300"
PWM_INT is 1
PWM_EXT is 0
@160
PWM_CNT is "0"
PWM_INT is 1
PWM_EXT is 0

/' --- Cycle 3 --- '/
@160
PWM_IRQ is "Active"
CPU is "Active"
@162
PWM_IRQ is "Idle"
CPU is "Idle"

@165
ALARM is "Active"
CPU is "Active"
@166
ALARM is "Idle"
ADC is "Active"
CPU is "Active"
ADC_CTRL is "EN,START_ONCE"
@167
CPU is "Idle"
DMA is "Transferring"
ADC -> DMA : DREQ
ADC_FIFO is "Filling"
@168
ADC -> DMA : DREQ
@169
ADC -> DMA : DREQ
@170
ADC -> DMA : DREQ

@175
DMA is "Idle"
ADC is "Idle"
DMA_IRQ is "Active"
ADC_CTRL is "Disabled"
ADC_FIFO is "Full"
@176
CPU is "Active"
@178
DMA_IRQ is "Idle"
CPU is "Idle"
ADC_FIFO is "Empty"

@160
PWM_CNT is "0"
PWM_INT is 1
PWM_EXT is 0
@167.5
PWM_CNT is "300"
PWM_INT is 0
PWM_EXT is 1
@185
PWM_CNT is "1000"
@202.5
PWM_CNT is "300"
PWM_INT is 1
PWM_EXT is 0
@210
PWM_CNT is "0"
PWM_INT is 1
PWM_EXT is 0


@enduml
