name: Build, Test and Package

on:
  push:
    branches:
      - '**'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: 'esp32:esp32:esp32'
            platform: 'esp32:esp32'
          - fqbn: 'nordic:nrf52:nrf52833'
            platform: 'nordic:nrf52'
          - fqbn: 'arduino:mbed_rp2040:pico'
            platform: 'arduino:mbed_rp2040'
          - fqbn: 'arduino:samd:mkr1000'
            platform: 'arduino:samd'
          - fqbn: 'STMicroelectronics:stm32:GenF1'
            platform: 'STMicroelectronics:stm32'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Initialize Arduino CLI configuration
        run: arduino-cli config init

      - name: Add board manager URLs
        run: |
          arduino-cli config set board_manager.additional_urls "https://espressif.github.io/arduino-esp32/package_esp32_index.json,https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json,https://raw.githubusercontent.com/adafruit/arduino-board-index/gh-pages/package_adafruit_index.json"
          echo "Attempting to curl Adafruit URL:"
          curl -vL "https://raw.githubusercontent.com/adafruit/arduino-board-index/gh-pages/package_adafruit_index.json"

      - name: Update core index
        run: arduino-cli core update-index --verbose

      - name: Install platform
        run: arduino-cli core install ${{ matrix.board.platform }}

      - name: Compile
        run: |
          arduino-cli compile --fqbn ${{ matrix.board.fqbn }} --warnings all .

  package:
    needs: build_and_test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Get release version'
        id: get_version
        uses: battila7/get-version-action@v2

      - name: 'Create archive'
        run: |
          zip -r xDuinoRails_MotorControl_bEMF-${{ steps.get_version.outputs.version-without-v }}.zip . -x ".git/*" ".github/*"

      - name: 'Upload release asset'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./xDuinoRails_MotorControl_bEMF-${{ steps.get_version.outputs.version-without-v }}.zip
          asset_name: xDuinoRails_MotorControl_bEMF-${{ steps.get_version.outputs.version-without-v }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
